# Generated by Django 5.0.6 on 2024-06-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='address',
        ),
        migrations.AddField(
            model_name='meter',
            name='address',
            field=models.ManyToManyField(to='meters.address'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='indication',
            field=models.PositiveIntegerField(),
        ),
    ]
